//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// (Hand-written to mirror controller-gen output; re-run `make generate` to refresh.)

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto for WorkloadRestoreRef.
func (in *WorkloadRestoreRef) DeepCopyInto(out *WorkloadRestoreRef) { *out = *in }

func (in *WorkloadRestoreRef) DeepCopy() *WorkloadRestoreRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRestoreRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for CheckpointInfo.
func (in *CheckpointInfo) DeepCopyInto(out *CheckpointInfo) { *out = *in }

func (in *CheckpointInfo) DeepCopy() *CheckpointInfo {
	if in == nil {
		return nil
	}
	out := new(CheckpointInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for GPURestoreSpec.
func (in *GPURestoreSpec) DeepCopyInto(out *GPURestoreSpec) {
	*out = *in
	out.WorkloadRestoreRef = in.WorkloadRestoreRef
	out.CheckpointInfo = in.CheckpointInfo
}

func (in *GPURestoreSpec) DeepCopy() *GPURestoreSpec {
	if in == nil {
		return nil
	}
	out := new(GPURestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for GPURestoreStatus.
func (in *GPURestoreStatus) DeepCopyInto(out *GPURestoreStatus) {
	*out = *in
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *GPURestoreStatus) DeepCopy() *GPURestoreStatus {
	if in == nil {
		return nil
	}
	out := new(GPURestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for GPURestore.
func (in *GPURestore) DeepCopyInto(out *GPURestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GPURestore) DeepCopy() *GPURestore {
	if in == nil {
		return nil
	}
	out := new(GPURestore)
	in.DeepCopyInto(out)
	return out
}

func (in *GPURestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for GPURestoreList.
func (in *GPURestoreList) DeepCopyInto(out *GPURestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]GPURestore, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *GPURestoreList) DeepCopy() *GPURestoreList {
	if in == nil {
		return nil
	}
	out := new(GPURestoreList)
	in.DeepCopyInto(out)
	return out
}

func (in *GPURestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for WorkloadTargetRef.
func (in *WorkloadTargetRef) DeepCopyInto(out *WorkloadTargetRef) { *out = *in }

func (in *WorkloadTargetRef) DeepCopy() *WorkloadTargetRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for CheckpointSourceRef.
func (in *CheckpointSourceRef) DeepCopyInto(out *CheckpointSourceRef) { *out = *in }

func (in *CheckpointSourceRef) DeepCopy() *CheckpointSourceRef {
	if in == nil {
		return nil
	}
	out := new(CheckpointSourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for WorkloadRestoreSpec.
func (in *WorkloadRestoreSpec) DeepCopyInto(out *WorkloadRestoreSpec) {
	*out = *in
	out.TargetWorkloadRef = in.TargetWorkloadRef
	if in.CheckpointRef != nil {
		out.CheckpointRef = new(CheckpointSourceRef)
		*out.CheckpointRef = *in.CheckpointRef
	}
}

func (in *WorkloadRestoreSpec) DeepCopy() *WorkloadRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for RestoreTargetStatus.
func (in *RestoreTargetStatus) DeepCopyInto(out *RestoreTargetStatus) { *out = *in }

func (in *RestoreTargetStatus) DeepCopy() *RestoreTargetStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for WorkloadRestoreStatus.
func (in *WorkloadRestoreStatus) DeepCopyInto(out *WorkloadRestoreStatus) {
	*out = *in
	if in.Targets != nil {
		l := make([]RestoreTargetStatus, len(in.Targets))
		copy(l, in.Targets)
		out.Targets = l
	}
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *WorkloadRestoreStatus) DeepCopy() *WorkloadRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for WorkloadRestore.
func (in *WorkloadRestore) DeepCopyInto(out *WorkloadRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *WorkloadRestore) DeepCopy() *WorkloadRestore {
	if in == nil {
		return nil
	}
	out := new(WorkloadRestore)
	in.DeepCopyInto(out)
	return out
}

func (in *WorkloadRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for WorkloadRestoreList.
func (in *WorkloadRestoreList) DeepCopyInto(out *WorkloadRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]WorkloadRestore, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *WorkloadRestoreList) DeepCopy() *WorkloadRestoreList {
	if in == nil {
		return nil
	}
	out := new(WorkloadRestoreList)
	in.DeepCopyInto(out)
	return out
}

func (in *WorkloadRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
